kind: pipeline
name: folker-test

steps:
  - name: test
    image: python:3.8-slim
    commands:
      - pip install -r requirements.txt
      - python3 -m unittest -v

  - name: integration-test
    image: python:3.8-slim
    commands:
      - pip install -r requirements.txt
      - mkdir /protos
      - mkdir /folker
      - cp -a ./folker.py         /
      - cp -a ./folker/*          /folker/
      - cp -a ./example/protos/*  /protos/
      - ls -la
      - cd /
      - sleep 5 # time for mockserver to start
      - ls -la
      - python3 folker.py --trace

  - name: bake-beta
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB.USER
      password:
        from_secret: DOCKERHUB.PASSWORD
      repo: folkertest/folkertest
      tags:
        - beta
        - "0.2.${DRONE_BUILD_NUMBER}"
    when:
      branch:
        - development
      event: push

  - name: bake
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB.USER
      password:
        from_secret: DOCKERHUB.PASSWORD
      repo: folkertest/folkertest
      tags:
        - latest
        - "0.2.${DRONE_BUILD_NUMBER}"
    when:
      branch:
        - master
        - release
      event: push

services:
  - name: mockserver
    # http://mockserver:1080
    image: mockserver/mockserver:latest
  - name: gcp-pubsub-emulator
    # gcp-pubsub-emulator:8681
    image: messagebird/gcloud-pubsub-emulator:latest
    environment:
      PUBSUB_PROJECT1: "folker-test-gcp-test,a_topic:a_subscription"
  - name: grpc-test-server
    # grpc-test-server:8682
    image: folkertest/grpc-test-server:latest