kind: pipeline
name: folker-test

steps:
  - name: test
    image: python:3.8-slim
    commands:
      - pip install -r requirements.txt
      - coverage run -m pytest -vv
      - coverage report -m

  - name: integration-test
    image: python:3.8-slim
    commands:
      - pip install -r requirements.txt
      - mkdir /folker
      - mkdir /protos
      - mkdir /testcode
      - mkdir /credentials
      - cp -a ./folker.py             /
      - cp -a ./folker/*              /folker
      - cp -a ./example/protos/*      /protos
      - cp -a ./example/code/*        /testcode
      - cp -a ./example/credentials/* /credentials
      - cd /
      - sleep 5 # time for assistant services to start
      - python3 folker.py -p test-profile -n 28 --trace
      - python3 folker.py -t dummy -t print -n 2 --trace
      - python3 folker.py -t dummy -t print --trace

  - name: bake-beta
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB.USER
      password:
        from_secret: DOCKERHUB.PASSWORD
      repo: folkertest/folkertest
      tags:
        - beta
        - "0.3.${DRONE_BUILD_NUMBER}"
    when:
      branch:
        - development
      event: push

  - name: bake
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB.USER
      password:
        from_secret: DOCKERHUB.PASSWORD
      repo: folkertest/folkertest
      tags:
        - latest
        - "0.3.${DRONE_BUILD_NUMBER}"
    when:
      branch:
        - master
        - release
      event: push

services:
    # http://mockserver:1080
  - name: mockserver
    image: mockserver/mockserver:latest

    # gcp-pubsub-emulator:8681
  - name: gcp-pubsub-emulator
    image: messagebird/gcloud-pubsub-emulator:latest
    environment:
      PUBSUB_PROJECT1: "folker-test-gcp-test,a_topic:a_subscription"

    # gcp-datastore-emulator:8684
  - name: gcp-datastore-emulator
    image: singularities/datastore-emulator
    environment:
      DATASTORE_PROJECT_ID: folker-test-gcp-test
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8684

    # grpc-test-server:8682
  - name: grpc-test-server
    image: folkertest/grpc-test-server:latest

    # graphql-test-server:8683
  - name: graphql-test-server
    image: folkertest/graphql-test-server:latest

    # postgres-server:5432
  - name: postgres-server
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker