kind: pipeline
name: folker-test

steps:
  - name: test
    image: python:3.8-slim
    commands:
      - pip install -r requirements.txt
      - python3 -m unittest -v

  - name: integration-test
    image: python:3.8-slim
    commands:
      - pip install -r requirements.txt
      - mkdir protos
      - ls -la
      - cp -a ./example/protos/* ./protos/
      - sleep 5 # time for mockserver to start
      - python3 folker.py -t

  - name: bake
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB.USER
      password:
        from_secret: DOCKERHUB.PASSWORD
      repo: folkertest/folkertest
      tags:
        - latest
        - "0.2.${DRONE_BUILD_NUMBER}"
    when:
      branch:
        - master
        - release
      event: push

services:
  - name: mockserver
    image: mockserver/mockserver:latest