version: '3.1'

services:
  mockserver:
    image: mockserver/mockserver:latest
    ports:
      - 1080:1080

  gcp-pubsub-emulator:
    image: messagebird/gcloud-pubsub-emulator:latest
    ports:
      - 8681:8681
    environment:
      PUBSUB_PROJECT1: "folker-test-gcp-test,a_topic:a_subscription"

  gcp-datastore-emulator:
    image: singularities/datastore-emulator
    ports:
      - 8684:8684
    environment:
      DATASTORE_PROJECT_ID: folker-test-gcp-test
      DATASTORE_LISTEN_ADDRESS: 0.0.0.0:8684

  grpc-test-server:
    image: folkertest/grpc-test-server:latest
    ports:
      - 8682:8682

  graphql-test-server:
    image: folkertest/graphql-test-server:latest
    ports:
      - 8683:8683

  postgres-server:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker

  integration-tests-1:
    build:
      context: .
      dockerfile: Dockerfile-integration
    command: -t dummy -t print --trace
  integration-tests-2:
    build:
      context: .
      dockerfile: Dockerfile-integration
    command: -t dummy -t print -n 2 --trace
  integration-tests-3:
    build:
      context: .
      dockerfile: Dockerfile-integration
    command: -p test-profile -n 28 --trace
    depends_on:
      - mockserver
      - gcp-pubsub-emulator
      - gcp-datastore-emulator
      - grpc-test-server
      - graphql-test-server
      - postgres-server
