FROM python:3.11-slim

WORKDIR /

RUN pip install --upgrade pip

COPY folker folker
COPY ./setup.py setup.py
RUN pip install -e .

COPY example/protos protos
COPY example/code testcode
COPY example/credentials credentials
COPY example/test test

ENTRYPOINT ["folker-test"]