version: 2.1

orbs:
  python: circleci/python@1.4.0

executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Test
          command: |
            coverage run -m pytest --junitxml codecoverage/unittests.xml
            coverage report -m
            coverage xml -o codecoverage/coverage.xml
            coverage html
      - store_test_results:
          path: codecoverage
      - store_artifacts:
          path: codecoverage
      - persist_to_workspace:
          root: .
          paths:
            - ./
      - run:
          name: Build Docker image
          command: |
            docker build -t folkertest:1.1.<<pipeline.number>> .
      - run:
          name: Archive Docker image
          command: docker save -o folkertest.tar folkertest
      - persist_to_workspace:
          root: .
          paths:
            - ./folkertest.tar

  setup-integration-tests-environment:
    machine: true # Linux VM instead of docker environment
    steps:
      - run:
          name: Create network
          command: |
            docker network create integration-test-network
      - run:
          name: startup mockserver
          command: |
            docker run --network integration-test-network \
            -d \
            --name mockserver \
            mockserver/mockserver:latest

  run-integration-tests:
    machine: true # Linux VM instead of docker environment
    steps:
      - run:
          name: Run int tests
          command: |
            echo "integration tests"

  terminate-integration-tests-environment:
    machine: true # Linux VM instead of docker environment
    steps:
        - run:
            name: Terminate mockserver
            command: docker stop mockserver
        - run:
            name: Terminate network
            command: docker network rm integration-test-network

workflows:
  main:
    jobs:
      - build
      - setup-integration-tests-environment:
          requires:
            - build
      - run-integration-tests:
          requires:
            - setup-integration-tests-environment
      - terminate-integration-tests-environment:
          requires:
            - run-integration-tests
