version: 2.1

orbs:
  python: circleci/python@1.4.0

executors:
  docker-builder:
    docker:
      - image: circleci/buildpack-deps:stretch
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Test
          command: |
            coverage run -m pytest --junitxml codecoverage/unittests.xml
            coverage report -m
            coverage xml -o codecoverage/coverage.xml
            coverage html
      - store_test_results:
          path: codecoverage
      - store_artifacts:
          path: codecoverage
      - persist_to_workspace:
          root: .
          paths:
            - ./

  build-docker-image:
    executor: docker-builder
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t folkertest:1.1.<<pipeline.number>> .
      - run:
          name: Archive Docker image
          command: docker save -o folkertest.tar folkertest
      - persist_to_workspace:
          root: .
          paths:
            - ./folkertest.tar

  integration-tests:
    machine: true # Linux VM instead of docker environment
    steps:
      - attach_workspace:
          at: .
      - run: docker-compose up -d mockserver
      - run: docker-compose up -d gcp-pubsub-emulator
      - run: docker-compose up -d gcp-datastore-emulator
      - run: docker-compose up -d grpc-test-server
      - run: docker-compose up -d graphql-test-server
      - run: docker-compose up -d postgres-server

      - run: docker-compose up integration-tests-template
      - run: docker-compose up integration-tests-profile
      - run: docker-compose up integration-tests-parallel
      - run: docker-compose up integration-tests-conditional
      - run: docker-compose up integration-tests-foreach
      - run: docker-compose up integration-tests-save
      - run: docker-compose up integration-tests-void
      - run: docker-compose up integration-tests-print
      - run: docker-compose up integration-tests-wait
      - run: docker-compose up integration-tests-rest
      - run: docker-compose up integration-tests-postgres
      - run: docker-compose up integration-tests-file
      - run: docker-compose up integration-tests-code
      - run: docker-compose up integration-tests-gmail
      - run: docker-compose up integration-tests-protobuf
      - run: docker-compose up integration-tests-grpc
      - run: docker-compose up integration-tests-graphql

      - run: docker-compose down

workflows:
  main:
    jobs:
      - build
      - integration-tests:
          requires:
            - build
      - build-docker-image:
          requires:
            - build
