id: apigee_template

stages:
  - id: apigee_authenticate
    name: Apigee authentication
    action:
      type: REST
      method: POST
      host: ${apigee_host}
      uri: oauth/client_credential/accesstoken?grant_type=client_credentials
      headers:
        Content-Type: application/x-www-form-urlencoded
      data:
        client_id: ${client_id}
        client_secret: ${client_secret}
    save:
      auth_access_token: ${response_json.access_token}

      shop_uri_v1: air/fares/shop/v1.0
      shop_uri_v2: air/fares/shop/v2.0
      price_uri_v1: air/fares/price/v1.0
      price_uri_v2: air/fares/price/v2.0
      conditions_uri: air/fares/conditions/v1.0
      book_uri: air/fares/book/v1.0

      utilities_host: https://partner-utilities.stg.travix.com
